services:

    patients-db:
        image: postgres:16
        container_name: patients-db
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-patientsdb}
            POSTGRES_USER: ${POSTGRES_USER:-patient_user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-patient_pass}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-patient_user} -d ${POSTGRES_DB:-patientsdb}"]
            interval: 5s
            timeout: 3s
            retries: 10

    notes-db:
        image: mongo:8.0.14
        container_name: notes-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-notes_user}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-notes_password}
        ports:
            - 27017:27017
        volumes:
            - database-data:/data/db

    ms-patients:
            build:
                context: ms-patients
                dockerfile: Dockerfile
            container_name: ms-patients
            profiles: ["fullstack"]
            depends_on:
                - patients-db
            environment:
                SPRING_PROFILES_ACTIVE: docker
                APP_USERNAME: ${APP_USERNAME:-app_user}
                APP_PASSWORD: ${APP_PASSWORD:-app_password}
            ports:
                - "9001:9001"

    ms-notes:
            build:
                context: ms-notes
                dockerfile: Dockerfile
            container_name: ms-notes
            profiles: ["fullstack"]
            depends_on:
                - notes-db
            environment:
                SPRING_PROFILES_ACTIVE: docker
                APP_USERNAME: ${APP_USERNAME:-app_user}
                APP_PASSWORD: ${APP_PASSWORD:-app_password}
            ports:
                - "9002:9002"

    ms-risque:
            build:
                context: ms-risque
                dockerfile: Dockerfile
            container_name: ms-risque
            profiles: ["fullstack"]
            depends_on:
                - ms-patients
                - ms-notes
            environment:
                SPRING_PROFILES_ACTIVE: docker
                APP_USERNAME: ${APP_USERNAME:-app_user}
                APP_PASSWORD: ${APP_PASSWORD:-app_password}
            ports:
                - "9003:9003"

    ms-gateway:
        build:
            context: ms-gateway
            dockerfile: Dockerfile
        container_name: ms-gateway
        profiles: ["fullstack"]
        depends_on:
            - ms-patients
            - ms-notes
            - ms-risque
        environment:
            SPRING_PROFILES_ACTIVE: docker
        ports:
            - "9000:9000"

    ms-clientui:
        build:
            context: ms-clientui
            dockerfile: Dockerfile
        container_name: ms-clienui
        profiles: ["fullstack"]
        depends_on:
            - ms-gateway
        environment:
            SPRING_PROFILES_ACTIVE: docker
            APP_USERNAME: ${APP_USERNAME:-app_user}
            APP_PASSWORD: ${APP_PASSWORD:-app_password}
        ports:
            - "8080:8080"

volumes:
  db_data:
  database-data:


