server:
  port: 8080

app:
  gateway:
    base-url: http://localhost:9000
  auth:
    username: ${APP_USERNAME:app_user}
    password: ${APP_PASSWORD:app_password}
spring:
  application:
    name: ms-clientui
