server:
  port: 9000

spring:
  application:
    name: ms-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-patients
              uri: http://ms-patients:9001
              predicates:
                - Path=/patients/**
            - id: ms-notes
              uri: http://ms-notes:9002
              predicates:
                - Path=/notes/**
            - id: ms-risque
              uri: http://ms-risque:9003
              predicates:
                - Path=/evaluation/**
