server:
  port: 9003

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ms-risque

services:
  patients-service:
    url: http://ms-patients:9001
  notes-service:
    url: http://ms-notes:9002

security:
  app-user:
    username: ${APP_USERNAME:app_user}
    password: ${APP_PASSWORD:app_password}


